// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129105301_Keys-KeyPriceTypeConstraint-Added")]
    partial class KeysKeyPriceTypeConstraintAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("API.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrebiCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JmaCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SilcaCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Keys", t =>
                        {
                            t.HasCheckConstraint("CK_Key_PriceType", "PriceType IN (1, 2, 3)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
